name: "Add AUR package"
description: "Add a new AUR package extracted from an issue."
inputs:
  token:
    required: true
    default: ${{ github.token }}
runs:
  using: "node12"
  main: "dist/index.js"
