on:
  issues:
    types: [opened]
name: Add AUR package
jobs:
  add-aur-package:
    runs-on: ubuntu-latest
    name: Add AUR package from created issue
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add AUR package
        uses: ./.github/actions/aur-add-package
