on: 
  workflow_dispatch:
  page_build:
name: Update Repository Database

jobs:
  update-repo-db:
    name: Update Repository Database
    runs-on: ubuntu-20.04
    steps:
      # TODO: lz4?
      - name: Install compression tools
        run: sudo apt-get install libarchive-tools ncompress gzip bzip2 lrzip lzop lzip xz-utils zstd

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: repository
          path: repository

      - name: Update repository database
        uses: ./main/.github/actions/repo-update-database
        with:
          repository: "repository"
          name: "jannikw-repo"

      - name: Publish updated database
        run: |
          git config --global user.email actions@github.com
          git config --global user.name 'Github Actions'
          git config --global core.editor true
          git reset --soft $(git rev-list --max-parents=0  HEAD)
          git add .
          git commit --amend -m "Update Repository" || true
          git push --force-with-lease
        working-directory: repository
